// frontend/src/components/FeaturedProducts.vue
<template>
  <div class="grid grid-cols-1 gap-y-4 sm:grid-cols-2 sm:gap-x-6 sm:gap-y-10 lg:grid-cols-3 lg:gap-x-8">
    <div
      v-for="product in featuredProducts"
      :key="product.id"
      class="group relative bg-white border border-gray-200 rounded-lg flex flex-col overflow-hidden hover:shadow-lg transition-shadow"
    >
      <div class="aspect-w-3 aspect-h-2 bg-gray-200 group-hover:opacity-75">
        <img
          :src="product.image"
          :alt="product.name"
          class="w-full h-full object-center object-cover"
        >
      </div>
      <div class="flex-1 p-4 space-y-2 flex flex-col">
        <h3 class="text-lg font-medium text-gray-900">
          <router-link :to="`/productos/${product.category}/${product.id}`">
            <span aria-hidden="true" class="absolute inset-0"></span>
            {{ product.name }}
          </router-link>
        </h3>
        <p class="text-sm text-gray-500">{{ product.description }}</p>
        <div class="flex-1 flex items-end">
          <div class="flex-1 flex justify-between items-center">
            <p class="text-lg font-medium text-purple-600">{{ product.price }} Bs.</p>
            <button
              @click.prevent="addToCart(product)"
              class="relative z-10 inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-purple-600 hover:bg-purple-700"
            >
              Añadir
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { useProductsStore } from '@/stores/products'
import { useCartStore } from '@/stores/cart'

const productsStore = useProductsStore()
const cartStore = useCartStore()

const featuredProducts = computed(() => productsStore.getFeaturedProducts)

const addToCart = (product) => {
  cartStore.addToCart(product)
}
</script>

// app/components/featured-products.tsx
import Link from "next/link"

import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

export function FeaturedProducts() {
  const featuredProducts = [
    {
      id: 1,
      name: "Windows 11 Pro",
      price: 350,
      image: "/placeholder.svg?height=200&width=300",
      category: "windows",
      badge: "Más vendido",
    },
    {
      id: 2,
      name: "Office 2021 Professional Plus",
      price: 420,
      image: "/placeholder.svg?height=200&width=300",
      category: "office",
      badge: "Oferta",
    },
    {
      id: 3,
      name: "Windows 10 Home",
      price: 280,
      image: "/placeholder.svg?height=200&width=300",
      category: "windows",
    },
    {
      id: 4,
      name: "Tarjeta Steam 50 USD",
      price: 380,
      image: "/placeholder.svg?height=200&width=300",
      category: "tarjetas",
      badge: "Nuevo",
    },
  ]

  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
      {featuredProducts.map((product) => (
        <Link href={`/productos/${product.category}/${product.id}`} key={product.id}>
          <Card className="h-full overflow-hidden transition-all hover:shadow-lg">
            <div className="relative">
              <img src={product.image || "/placeholder.svg"} alt={product.name} className="w-full h-48 object-cover" />
              {product.badge && <Badge className="absolute top-2 right-2 bg-blue-600">{product.badge}</Badge>}
            </div>
            <CardHeader className="p-4">
              <CardTitle className="text-lg text-purple-900">{product.name}</CardTitle>
            </CardHeader>
            <CardContent className="p-4 pt-0">
              <p className="text-sm text-gray-500">Licencia digital - Entrega inmediata</p>
            </CardContent>
            <CardFooter className="p-4 flex justify-between items-center">
              <p className="text-xl font-bold text-purple-900">{product.price} Bs.</p>
              <Badge variant="outline" className="bg-purple-100 text-purple-800 hover:bg-purple-200">
                Ver detalles
              </Badge>
            </CardFooter>
          </Card>
        </Link>
      ))}
    </div>
  )
}
